### ISSUE TITLE
Unexpected keyword argument in roundabout.run

### ISSUE THREAD

**Issue by ChristopherMacGown** [ChristopherMacGown/roundabout#42]
[03-03-2011 16:05:28] processing https://github.com/gem/openquake/pull/70
[03-03-2011 16:06:07] Cloning to /tmp/repos/openquake/pUvEssrS
[03-03-2011 16:06:07] merging remotes/larsbutler/cpt-file-reader into master
[03-03-2011 16:06:07] pushing :merge_cpt-file-reader to origin
Traceback (most recent call last):
  File "/usr/local/bin/roundabout", line 5, in <module>
    pkg_resources.run_script('roundabout==0.15', 'roundabout')
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 467, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 1200, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.6/dist-packages/roundabout-0.15-py2.6.egg/EGG-INFO/scripts/roundabout", line 22, in <module>
    roundabout.main(args[0], options)
  File "/usr/local/lib/python2.6/dist-packages/roundabout-0.15-py2.6.egg/roundabout/**init**.py", line 41, in main
    run(config)
  File "/usr/local/lib/python2.6/dist-packages/roundabout-0.15-py2.6.egg/roundabout/**init**.py", line 91, in run
    cfg=config, path=repo.clonepath)
TypeError: **init**() got an unexpected keyword argument 'cfg'

**Comment by ChristopherMacGown** [comment]
Closed by 17267e6b8fd2cb3f04406ff3f139a68587f46fc7
