### ISSUE TITLE
Stack trace while processing https://github.com/gem/openquake/pull/82

### ISSUE THREAD

**Issue by al-maisan** [ChristopherMacGown/roundabout#46]
The error below might be occurring because I am approving my own branch?

Also, I would expect such an error (including the stack trace) to be written
to the log file, I only got to see the error because I ssh'ed into the slice
restarted the mergebot and waited..

> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/roundabout", line 5, in <module>
>     pkg_resources.run_script('roundabout==0.15.1', 'roundabout')
>   File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 467, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 1200, in run_script
>     execfile(script_filename, namespace, namespace)
>   File "/usr/local/lib/python2.6/dist-packages/roundabout-0.15.1-py2.6.egg/EGG-INFO/scripts/roundabout", line 22, in <module>
>     roundabout.main(args[0], options)
>   File "/usr/local/lib/python2.6/dist-packages/roundabout-0.15.1-py2.6.egg/roundabout/__init__.py", line 41, in main
>     run(config)
>   File "/usr/local/lib/python2.6/dist-packages/roundabout-0.15.1-py2.6.egg/roundabout/__init__.py", line 73, in run
>     config=config)
>   File "/usr/local/lib/python2.6/dist-packages/roundabout-0.15.1-py2.6.egg/roundabout/git_client.py", line 40, in __init__
>     self.clonepath)
>   File "/usr/local/lib/python2.6/dist-packages/git/repo/base.py", line 726, in clone_from
>     return cls._clone(Git(os.getcwd()), url, to_path, GitCmdObjectDB, **kwargs)
>   File "/usr/local/lib/python2.6/dist-packages/git/repo/base.py", line 701, in _clone
>     repo.remotes[0].config_writer.set_value('url', repo.remotes[0].url.replace("\\\\", "\\").replace("\\", "/"))
>   File "/usr/local/lib/python2.6/dist-packages/git/remote.py", line 421, in __getattr__
>     return self._config_reader.get(attr)
>   File "/usr/local/lib/python2.6/dist-packages/git/config.py", line 86, in <lambda>
>     return lambda *args, **kwargs: self._call_config(attr, *args, **kwargs)
>   File "/usr/local/lib/python2.6/dist-packages/git/config.py", line 92, in _call_config
>     return getattr(self._config, method)(self._section_name, *args, **kwargs)
>   File "/usr/local/lib/python2.6/dist-packages/git/config.py", line 52, in assure_data_present
>     self.read()
>   File "/usr/local/lib/python2.6/dist-packages/git/config.py", line 290, in read
>     self._read(fp, fp.name)
>   File "/usr/local/lib/python2.6/dist-packages/git/config.py", line 261, in _read
>     raise e
> ConfigParser.ParsingError: File contains parsing errors: /home/muharem/.gitconfig
>     [line  7]: '    ci = commit\n'
>     [line  8]: '    co = checkout\n'
> ```

**Comment by al-maisan** [comment]
This was my mistake .. I had a superfluous .gitconfig in my $HOME and roundabout stumbled across that.

Thanks to Lars for spotting that!
